spring:
  application:
    name: todo-pro-api
  profiles:
    active: dev # Define que o perfil 'dev' será o padrão ao iniciar
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # Útil se o banco já tiver tabelas
  jackson:
    serialization:
      write-dates-as-timestamps: false
  config:
    import: optional:file:.env[.properties]

api:
  security:
    token:
      secret: ${JWT_SECRET}